### ISSUE TITLE
Script error when i try declarate directory.

### ISSUE THREAD

**Issue by patrykgielo** [tarun29061990/less-scss-convertor#3]
Hi, i tried declare the path to directory, but script sends me an error message, expects filename not directory

My command was: **$ less-scss-convertor css/** in this folder i have my less files and more directories with less files

```
Starting
fs.js:731
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at C:\Users\p.gielo\AppData\Roaming\npm\node_modules\less-scss-convertor\lib\server.js:43:20
    at Array.forEach (native)
    at C:\Users\p.gielo\AppData\Roaming\npm\node_modules\less-scss-convertor\lib\server.js:40:12
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

**Comment by tarun29061990** [comment]
Can you remove the '/' from the directory name and try ?

**Comment by patrykgielo** [comment]
I tried with slash, without and 10 others configuration, all return errors when i declare path not file. Maybe i need specific node version?

**Comment by patrykgielo** [comment]
Okay i debugged your code and i find problem. I have more directories in my css folder, when script find directory instead of files then return errors. Can you fix this?

**Comment by tarun29061990** [comment]
Yeah It doesn't check for subdirectories. For the time being can you do one folder at a time (directory/subDirectory) , meanwhile I will fix this.
